[package]
name = "vi-config"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[lints]
workspace = true

[features]
default = []
json = ["dep:serde_json"]

[dependencies]
vi-core = { path = "../vi-core" }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
notify = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
