[package]
name = "vi-fcitx5"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
vi-core = { path = "../vi-core" }
vi-platform = { path = "../vi-platform" }
tracing = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
