[package]
name = "vi-x11"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
vi-core = { path = "../vi-core" }
vi-platform = { path = "../vi-platform" }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
x11rb = { workspace = true, features = ["randr"] }
xkbcommon = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
